function nospecials(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1<"abcdefghijklmnopqrstuvwxyz0123456789_-.() ".indexOf(b)?!0:!1}
function logins(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1<"abcdefghijklmnopqrstuvwxyz0123456789_-.".indexOf(b)?!0:!1}
function justemails(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1<"abcdefghijklmnopqrstuvwxyz0123456789+_-@.".indexOf(b)?!0:!1}function numbersonly(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1<"0123456789.".indexOf(b)?!0:!1}
function noquotes(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1!="\"'".indexOf(b)?!1:!0}function noquotestags(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1!="\"'<>".indexOf(b)?!1:!0}
function noquotestagscomma(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1!="\"'<>,".indexOf(b)?!1:!0}function notags(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1!="<>".indexOf(b)?!1:!0}
function justips(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;var b=String.fromCharCode(a);b=b.toLowerCase();return null==a||0==a||8==a||9==a||13==a||27==a?!0:-1<"abcdefghijklmnopqrstuvwxyz0123456789.:*".indexOf(b)?!0:!1}function check_email(a){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(a)}
function do_alert(a,b,c){var d=a?3E3:4E3;b&&600<b.length?d=14E3:b&&100<b.length&&(d=5E3);"undefined"!=typeof c&&(d=1E3*parseInt(c));!a&&b&&0==b.indexOf("Authentication error")&&0<location.href.indexOf("/setup/")&&(location.href="../logout.php?&errno=621&menu=sa&action=logout");$("#login_alert_box").length&&$("#login_alert_box").remove();c=a?'<div class="info_good" style="text-align: center; padding: 25px; font-size: 14px; font-weight: bold; border-width: 2px; box-shadow: 0px 0px 25px rgba(0, 0, 0, 0.2);">'+
b+"</div>":'<div class="info_error" style="text-align: center; padding: 25px; font-size: 14px; font-weight: bold; border-width: 2px; box-shadow: 0px 0px 25px rgba(0, 0, 0, 0.2);">'+b+"</div>";a||"undefined"==typeof isop||!isop||b.match(/(must be active)|(blank)/i)||(a=$("#error_message").val()?$("#error_message").val()+"\r\n":"",b="["+unixtime()+"] "+b,$("#error_message").val(a+b));location.href.match(/\/(setup|addons)/i)?(b=location.href.match(/setup/i)?"..":"../..",$("body").append('<div id="login_alert_box" class="round" style="display: none; position: absolute; top: 0px; left: 0px; background: url('+
b+'/themes/initiate/bg_trans_darker.png) repeat; padding: 15px; z-Index: 10010;" onClick="$(this).hide();">'+c+"</div>")):$("body").append('<div id="login_alert_box" style="display: none; position: absolute; top: 0px; left: 0px; z-Index: 10010;" onClick="$(this).hide();">'+c+"</div>");$("#login_alert_box").center().show().fadeOut("slow").fadeIn("fast").delay(d).fadeOut("slow").hide()}
function do_alert_div(a,b,c){b?$("#div_alert").removeClass("info_good").removeClass("info_error").addClass("info_good").html(c):$("#div_alert").removeClass("info_good").removeClass("info_error").addClass("info_error").html(c);$("#div_alert").fadeIn("fast")}
function do_search(a){var b=$("#console").length&&1==parseInt($("#console").val())?1:0,c=$("#deptid").val()?$("#deptid").val():0,d=$("#opid").val()?$("#opid").val():0,g=$("#tid").val()?$("#tid").val():0,e=encodeURIComponent($("#input_search").val().trim()),k=$("#s_as").val(),p=$("#month").val(),f=$("#year").val();if(k&&!e)return $("#input_search").focus(),do_alert(0,"Search Text must be provided if searching a field."),!1;if(!k&&e)return do_alert(0,"Search Field must be selected if searching a text."),
$("#s_as").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast"),!1;if(!(parseInt(g)||e||k||parseInt(p)||parseInt(f))){if("undefined"!=typeof global_ces&&!parseInt(c)&&!parseInt(d)||"undefined"==typeof global_ces)return do_alert(0,"At least one search criteria must be selected."),setTimeout(function(){$("#tr_search_criteria").fadeTo("fast",.1).fadeTo("fast",1).fadeTo("fast",.1).fadeTo("fast",1).fadeTo("fast",.1).fadeTo("fast",1)},1E3),!1}else if(p&&!parseInt(f))return do_alert(0,
"Year must be selected."),$("#year").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast"),!1;$("#btn_page_search").val("searching...").attr("disabled",!0);setTimeout(function(){location.href=a+"?action=search&deptid="+c+"&opid="+d+"&tid="+g+"&m="+p+"&y="+f+"&s_as="+k+"&console="+b+"&text="+e},1E3)}function toggle_search_trans(a){$("#div_trans_search").is(":visible")||a?$("#div_trans_search").fadeOut("fast"):$("#div_trans_search").fadeIn("fast")}
window.unixtime=function(){return parseInt((new Date).getTime().toString().substring(0,10))};function microtime(a){var b=(new Date).getTime()/1E3,c=parseInt(b,10);return a?b:Math.round(1E3*(b-c))/1E3+" "+c}function pad(a,b){for(var c=""+a;c.length<b;)c="0"+c;return c}function autolink_it(a){null!=/^\/nolink /i.exec(a)&&(a=a.replace(/^\/nolink /i,"").replace(/\//g,"&#47;").replace(/\./g,"&#46;"));return autolinker.link(a)}
function new_win_default(a){var b=unixtime();window.open(a,b,"scrollbars=yes,menubar=yes,resizable=1,location=yes,toolbar=yes,status=1")}var is_ios=0,is_android=0;function is_mobile(){var a=navigator.userAgent||navigator.vendor||window.opera;if(a.match(/iPad/i)||a.match(/iPhone/i)||a.match(/iPod/i))return is_ios=1,a.match(/iPad/i)?3:1;a.match(/Android/i)&&(is_android=1);return 2}
function randomstring(a){for(var b="",c=0;c<a;c++)b+="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789".charAt(Math.floor(57*Math.random()));return b}function seconds_to_hhmmss(a){a=Number(a);var b=pad(Math.floor(a/3600),2),c=pad(Math.floor(a%3600/60),2);a=pad(Math.floor(a%3600%60),2);return b+":"+c+":"+a}
function External_lib_PopupCenter(a,b,c,d,g){var e=window.open(a,b,g+", top="+((window.innerHeight?window.innerHeight:document.documentElement.clientHeight?document.documentElement.clientHeight:screen.height)/2-d/2+(void 0!=window.screenTop?window.screenTop:screen.top))+", left="+((window.innerWidth?window.innerWidth:document.documentElement.clientWidth?document.documentElement.clientWidth:screen.width)/2-c/2+(void 0!=window.screenLeft?window.screenLeft:screen.left)));setTimeout(function(){e.focus()},
300);return e}function Is_Chrome(){var a=window.chrome,b=window.navigator,c=b.vendor,d="undefined"!==typeof window.opr,g=-1<b.userAgent.indexOf("Edge");return b.userAgent.match("CriOS")?!0:null!==a&&"undefined"!==typeof a&&"Google Inc."===c&&!0===d&&!1===g?!0:!1}function obj_length(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}
function HTML5_audio_support(){var a={};Modernizr.audio&&(a.audio=1,Modernizr.audio.mp3&&(a.mp3=1),Modernizr.audio.ogg&&(a.ogg=1),Modernizr.audio.m4a&&(a.m4a=1));return a}var undeefined;String.prototype.trimreturn=function(){return"\r\n"==this.substr(this.length-2,this.length)?this.substr(0,this.length-2):"\n"==this.substr(this.length-1,this.length)?this.substr(0,this.length-1):this};
String.prototype.noreturns=function(){return this.replace(/(\r\n)/g," p_br ").replace(/(\r)/g," p_br ").replace(/(\n)/g," p_br ")};String.prototype.nl2br=function(){return this.replace(/( p_br )/g,"<br>")};String.prototype.tags=function(){return this.replace(/>/g,"&gt;").replace(/</g,"&lt;")};String.prototype.nquotes=function(){return this.replace(/"/g,"").replace(/'/g,"")};String.prototype.curlys=function(){return this.replace(/{/g,"&#123;").replace(/}/g,"&#125;")};
String.prototype.brackets=function(){return this.replace(/\[/g,"&#91;").replace(/\]/g,"&#93;")};String.prototype.tabs=function(){return this.replace(/\t/g," ")};String.prototype.slashes=function(){return this.replace(/\\/g,"&#92;")};String.prototype.c615=function(){return this.replace(/<c615>(.*?)<\/c615>/g,"")};
String.prototype.vars=function(a){var b="undefined"!=typeof chats&&"undefined"!=typeof chats[ces]?chats[ces].vname:"",c="undefined"!=typeof chats?cname:"",d="undefined"!=typeof chats?cemail:"",g="undefined"!=typeof ces?ces:"";a&&(b=a);a=this.replace(/((%%user%%)|(%%visitor%%))/gi,"<span class='notranslate'>"+b+"</span>");a=a.replace(/%%operator%%/gi,"<span class='notranslate'>"+c+"</span>");a=a.replace(/%%op_email%%/gi,"<a tag='link' href='mailto:"+d+"' class='notranslate' target='"+phplive_link_target+
"'>"+d+"</a>");return a=a.replace(/%%chatid%%/gi,"<span class='notranslate'>"+g+"</span>")};String.prototype.xvis=function(){return this.replace(/<x-vis>(.*?)<\/x-vis>/g,"")};
String.prototype.vars_global=function(){var a=this;-1!=a.toLowerCase().indexOf("screenshot:")||-1!=a.toLowerCase().indexOf("image:")||-1!=a.toLowerCase().indexOf("image_nolink:")||0===a.toLowerCase().indexOf("pdf:")||0===a.toLowerCase().indexOf("txt:")||0===a.toLowerCase().indexOf("conf:")||0===a.toLowerCase().indexOf("zip:")||0===a.toLowerCase().indexOf("tar:")?a.match(/screenshot:(.*?):name:(.*?):url:(.*?)($| |<br>)/i)?a=a.replace(/screenshot:(.*?):name:(.*?):url:(.*?)($| |<br>)/ig,function(b,c,
d,g){return"<div style='padding: 5px; margin-bottom: 5px;' class=''><a tag='link' href='"+base_url_full+"/view.php?file="+encodeURIComponent(d)+"' target='"+phplive_link_target+"'><img src='"+c+"' style='max-width: 100%; max-height: 100%;' border=0 class='round'><br>"+d+"</a><x-vis><div style='margin-top: 15px;'><a tag='href' href='"+g+"' target='"+phplive_link_target+"'>"+g+"</a></div></x-vis></div> "}):a.match(/image:(.*?):name:(.*?)($| |<br>)/i)?a=a.replace(/image:(.*?):name:(.*?)($| |<br>)/ig,
function(b,c,d){return"<div style='padding: 5px; margin-bottom: 5px;' class=''><a tag='link' href='"+base_url_full+"/view.php?file="+encodeURIComponent(d)+"' target='"+phplive_link_target+"'><img src='"+c+"' style='max-width: 100%; max-height: 100%;' border=0 class='round'><br>"+d+"</a></div> "}):a.match(/image:(.*?)($| |<br>)/i)?a=a.replace(/image:(.*?)($| |<br>)/ig,"<div style='padding: 5px; margin-bottom: 5px;' class=''><a tag='link' href='$1' target='"+phplive_link_target+"'><img src='$1' style='max-width: 100%; max-height: 100%;' border=0 class='round'></a></div> "):
a.match(/image_nolink:(.*?)($| |<br>)/i)?a=a.replace(/image_nolink:(.*?)($| |<br>)/ig,"<div style='padding: 5px; margin-bottom: 5px;' class=''><img src='$1' style='max-width: 100%; max-height: 100%;' border=0 class='round'></div> "):a.match(/pdf:(.*?)($| |<br>)/i)?a=a.replace(/pdf:(.*?)($| |<br>)/ig,function(b,c,d){return"<div style='padding: 5px; margin-bottom: 5px;'><span class=''><a tag='link' href='"+base_url_full+"/view.php?file="+encodeURIComponent(c)+"' target='"+phplive_link_target+"'><img src='"+
base_url_full+"/pics/icons/pdf.gif' width='50' height='50' border=0 class='round'> "+c+"</a></span></div> "}):a.match(/txt:(.*?)($| |<br>)/i)?a=a.replace(/txt:(.*?)($| |<br>)/ig,function(b,c,d){return"<div style='padding: 5px; margin-bottom: 5px;'><span class=''><a tag='link' href='"+base_url_full+"/view.php?file="+encodeURIComponent(c)+"' target='"+phplive_link_target+"'><img src='"+base_url_full+"/pics/icons/txt.gif' width='50' height='50' border=0 class='round'> "+c+"</a></span></div> "}):a.match(/conf:(.*?)($| |<br>)/i)?
a=a.replace(/conf:(.*?)($| |<br>)/ig,function(b,c,d){return"<div style='padding: 5px; margin-bottom: 5px;'><span class=''><a tag='link' href='"+base_url_full+"/view.php?file="+encodeURIComponent(c)+"' target='"+phplive_link_target+"'><img src='"+base_url_full+"/pics/icons/conf.gif' width='50' height='50' border=0 class='round'> "+c+"</a></span></div> "}):a.match(/zip:(.*?)($| |<br>)/i)?a=a.replace(/zip:(.*?)($| |<br>)/ig,function(b,c,d){return"<div style='padding: 5px; margin-bottom: 5px;'><span class=''><a tag='link' href='"+
base_url_full+"/view.php?file="+encodeURIComponent(c)+"' target='"+phplive_link_target+"'><img src='"+base_url_full+"/pics/icons/zip.gif' width='50' height='50' border=0 class='round'> "+c+"</a></span></div> "}):a.match(/tar:(.*?)($| |<br>)/i)&&(a=a.replace(/tar:(.*?)($| |<br>)/ig,function(b,c,d){return"<div style='padding: 5px; margin-bottom: 5px;'><span class=''><a tag='link' href='"+base_url_full+"/view.php?file="+encodeURIComponent(c)+"' target='"+phplive_link_target+"'><img src='"+base_url_full+
"/pics/icons/tar.gif' width='50' height='50' border=0 class='round'> "+c+"</a></span></div> "})):!a.match(/^\/nolink /)&&a.match(/(https?:\/\/\S+(\.png|\.jpg|\.jpeg|\.gif|\.svg|\.webp)($| ))/i)&&(a=a.replace(/(https?:\/\/\S+(\.png|\.jpg|\.jpeg|\.gif|\.svg|\.webp))/ig,"<div style='padding: 5px; margin-bottom: 5px;' class=''><a tag='image' href='$1' target='"+phplive_link_target+"'><img src='$1' style='max-width: 100%; max-height: 100%;' border=0 class='round'></a></div> "));return a};
String.prototype.emos=function(){var a=this;"undefined"!=typeof addon_emo&&parseInt(addon_emo)&&(a=a.replace(/(&lt;3)/g,"<img src='"+base_url+"/addons/emoticons/heart.png' width='18' height='18' border='0'>"),a=a.replace(/(&gt;:\()/g,"<img src='"+base_url+"/addons/emoticons/angry.png' width='18' height='18' border='0'>"),a=a.replace(/(:\))/g,"<img src='"+base_url+"/addons/emoticons/smile.png' width='18' height='18' border='0'>"),a=a.replace(/(:\()/g,"<img src='"+base_url+"/addons/emoticons/sad.png' width='18' height='18' border='0'>"),
a=a.replace(/(:\\)/g,"<img src='"+base_url+"/addons/emoticons/confused.png' width='18' height='18' border='0'>"),a=a.replace(/(:&#39;\()/g,"<img src='"+base_url+"/addons/emoticons/cry.png' width='18' height='18' border='0'>"),a=a.replace(/(:\$)/g,"<img src='"+base_url+"/addons/emoticons/embarrassed.png' width='18' height='18' border='0'>"),a=a.replace(/(:-D)/g,"<img src='"+base_url+"/addons/emoticons/ecstatic.png' width='18' height='18' border='0'>"),a=a.replace(/(:\|)/g,"<img src='"+base_url+"/addons/emoticons/neutral.png' width='18' height='18' border='0'>"),
a=a.replace(/(\|_)/g,"<img src='"+base_url+"/addons/emoticons/thumbs_up.png' width='18' height='18' border='0'>"),a=a.replace(/(;\))/g,"<img src='"+base_url+"/addons/emoticons/wink.png' width='18' height='18' border='0'>"),a=a.replace(/(:-O)/g,"<img src='"+base_url+"/addons/emoticons/omg.png' width='18' height='18' border='0'>"));return a};"function"!==typeof String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});var phplive_wp;
function init_menu(){$("*","body").each(function(){$(this).attr("id");"menu"==$(this).attr("class")&&$(this).hover(function(){"menu_focus"!=$(this).attr("class")&&$(this).removeClass("menu").addClass("menu_hover")},function(){"menu_focus"!=$(this).attr("class")&&$(this).removeClass("menu_hover").addClass("menu")})})}
function init_menu_op(){$("*","body").each(function(){$(this).attr("id");"menu"==$(this).attr("class")&&$(this).hover(function(){"menu_focus"!=$(this).attr("class")&&$(this).removeClass("menu").addClass("menu_hover")},function(){"menu_focus"!=$(this).attr("class")&&$(this).removeClass("menu_hover").addClass("menu")})})}
function toggle_menu_op(a){var b={go:"",activity:"",reports:"",themes:"",notifications:"",settings:""},c;for(c in b)$("#menu_"+c).removeClass("menu_focus").addClass("menu"),$("#op_"+c).hide();menu=a;$("#menu_"+a).removeClass("menu").removeClass("menu_hover").addClass("menu_focus");$("#op_"+a).show()}function logout_op(){location.href="../logout.php?action=logout"}
function toggle_menu_setup(a){for(var b="home depts ops icons html trans rchats rtraffic interface settings extras".split(" "),c=0;c<b.length;++c)$("#menu_"+b[c]).removeClass("menu_focus").addClass("menu");$("#menu_"+a).removeClass("menu").removeClass("menu_hover").addClass("menu_focus");menu=a}
function preview_theme(a,b,c,d){var g=unixtime(),e="_blank";"undefined"!=typeof mapp&&mapp&&(e="_system");var k=window.open("../phplive.php?d="+d+"&theme="+a+"&preview=1&"+g,"theme_preview","scrollbars=no,resizable=yes,menubar=no,location=no,screenX=50,screenY=100,width="+b+",height="+c,e,"location=yes");setTimeout(function(){k.focus()},300)}
function phplive_utf8_encode(a){if(null===a||"undefined"==typeof a)return"";var b,c=a+"",d="";a=b=0;var g=c.length;for(var e=0;g>e;e++){var k=c.charCodeAt(e),p=null;if(128>k)b++;else if(127<k&&2048>k)p=String.fromCharCode(k>>6|192,63&k|128);else if(55296!=(63488&k))p=String.fromCharCode(k>>12|224,k>>6&63|128,63&k|128);else{if(55296!=(64512&k))throw new RangeError("Unmatched trail surrogate at "+e);p=c.charCodeAt(++e);if(56320!=(64512&p))throw new RangeError("Unmatched lead surrogate at "+(e-1));k=
((1023&k)<<10)+(1023&p)+65536;p=String.fromCharCode(k>>18|240,k>>12&63|128,k>>6&63|128,63&k|128)}null!==p&&(b>a&&(d+=c.slice(a,b)),d+=p,a=b=e+1)}return b>a&&(d+=c.slice(a,g)),d}
function phplive_md5(a){var b,c=function(q,t){var v,u,x,r,w;return x=2147483648&q,r=2147483648&t,v=1073741824&q,u=1073741824&t,w=(1073741823&q)+(1073741823&t),v&u?2147483648^w^x^r:v|u?1073741824&w?3221225472^w^x^r:1073741824^w^x^r:w^x^r},d=function(q,t,v,u,x,r,w){return q=c(q,c(c(t&v|~t&u,x),w)),c(q<<r|q>>>32-r,t)},g=function(q,t,v,u,x,r,w){return q=c(q,c(c(t&u|v&~u,x),w)),c(q<<r|q>>>32-r,t)},e=function(q,t,v,u,x,r,w){return q=c(q,c(c(t^v^u,x),w)),c(q<<r|q>>>32-r,t)},k=function(q,t,v,u,x,r,w){return q=
c(q,c(c(v^(t|~u),x),w)),c(q<<r|q>>>32-r,t)},p=function(q){var t,v="";for(t=0;3>=t;t++){var u=q>>>8*t&255;u="0"+u.toString(16);v+=u.substr(u.length-2,2)}return v},f=[];a=this.phplive_utf8_encode(a);f=function(q){var t=q.length,v=t+8;v=16*((v-v%64)/64+1);for(var u=Array(v-1),x=0,r=0;t>r;){var w=(r-r%4)/4;x=r%4*8;u[w]|=q.charCodeAt(r)<<x;r++}return w=(r-r%4)/4,x=r%4*8,u[w]|=128<<x,u[v-2]=t<<3,u[v-1]=t>>>29,u}(a);var h=1732584193;var m=4023233417;var l=2562383102;var n=271733878;a=f.length;for(b=0;a>
b;b+=16){var A=h;var z=m;var B=l;var y=n;h=d(h,m,l,n,f[b+0],7,3614090360);n=d(n,h,m,l,f[b+1],12,3905402710);l=d(l,n,h,m,f[b+2],17,606105819);m=d(m,l,n,h,f[b+3],22,3250441966);h=d(h,m,l,n,f[b+4],7,4118548399);n=d(n,h,m,l,f[b+5],12,1200080426);l=d(l,n,h,m,f[b+6],17,2821735955);m=d(m,l,n,h,f[b+7],22,4249261313);h=d(h,m,l,n,f[b+8],7,1770035416);n=d(n,h,m,l,f[b+9],12,2336552879);l=d(l,n,h,m,f[b+10],17,4294925233);m=d(m,l,n,h,f[b+11],22,2304563134);h=d(h,m,l,n,f[b+12],7,1804603682);n=d(n,h,m,l,f[b+13],
12,4254626195);l=d(l,n,h,m,f[b+14],17,2792965006);m=d(m,l,n,h,f[b+15],22,1236535329);h=g(h,m,l,n,f[b+1],5,4129170786);n=g(n,h,m,l,f[b+6],9,3225465664);l=g(l,n,h,m,f[b+11],14,643717713);m=g(m,l,n,h,f[b+0],20,3921069994);h=g(h,m,l,n,f[b+5],5,3593408605);n=g(n,h,m,l,f[b+10],9,38016083);l=g(l,n,h,m,f[b+15],14,3634488961);m=g(m,l,n,h,f[b+4],20,3889429448);h=g(h,m,l,n,f[b+9],5,568446438);n=g(n,h,m,l,f[b+14],9,3275163606);l=g(l,n,h,m,f[b+3],14,4107603335);m=g(m,l,n,h,f[b+8],20,1163531501);h=g(h,m,l,n,f[b+
13],5,2850285829);n=g(n,h,m,l,f[b+2],9,4243563512);l=g(l,n,h,m,f[b+7],14,1735328473);m=g(m,l,n,h,f[b+12],20,2368359562);h=e(h,m,l,n,f[b+5],4,4294588738);n=e(n,h,m,l,f[b+8],11,2272392833);l=e(l,n,h,m,f[b+11],16,1839030562);m=e(m,l,n,h,f[b+14],23,4259657740);h=e(h,m,l,n,f[b+1],4,2763975236);n=e(n,h,m,l,f[b+4],11,1272893353);l=e(l,n,h,m,f[b+7],16,4139469664);m=e(m,l,n,h,f[b+10],23,3200236656);h=e(h,m,l,n,f[b+13],4,681279174);n=e(n,h,m,l,f[b+0],11,3936430074);l=e(l,n,h,m,f[b+3],16,3572445317);m=e(m,l,
n,h,f[b+6],23,76029189);h=e(h,m,l,n,f[b+9],4,3654602809);n=e(n,h,m,l,f[b+12],11,3873151461);l=e(l,n,h,m,f[b+15],16,530742520);m=e(m,l,n,h,f[b+2],23,3299628645);h=k(h,m,l,n,f[b+0],6,4096336452);n=k(n,h,m,l,f[b+7],10,1126891415);l=k(l,n,h,m,f[b+14],15,2878612391);m=k(m,l,n,h,f[b+5],21,4237533241);h=k(h,m,l,n,f[b+12],6,1700485571);n=k(n,h,m,l,f[b+3],10,2399980690);l=k(l,n,h,m,f[b+10],15,4293915773);m=k(m,l,n,h,f[b+1],21,2240044497);h=k(h,m,l,n,f[b+8],6,1873313359);n=k(n,h,m,l,f[b+15],10,4264355552);
l=k(l,n,h,m,f[b+6],15,2734768916);m=k(m,l,n,h,f[b+13],21,1309151649);h=k(h,m,l,n,f[b+4],6,4149444226);n=k(n,h,m,l,f[b+11],10,3174756917);l=k(l,n,h,m,f[b+2],15,718787259);m=k(m,l,n,h,f[b+9],21,3951481745);h=c(h,A);m=c(m,z);l=c(l,B);n=c(n,y)}return(p(h)+p(m)+p(l)+p(n)).toLowerCase()}
var phplive_base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",c=0;for(a=phplive_base64._utf8_encode(a);c<a.length;){var d=a.charCodeAt(c++),g=a.charCodeAt(c++),e=a.charCodeAt(c++),k=d>>2;d=(d&3)<<4|g>>4;var p=(g&15)<<2|e>>6,f=e&63;isNaN(g)?p=f=64:isNaN(e)&&(f=64);b=b+this._keyStr.charAt(k)+this._keyStr.charAt(d)+this._keyStr.charAt(p)+this._keyStr.charAt(f)}return b},decode:function(a){var b="",c=0;for(a=a.replace(/[^A-Za-z0-9\+\/=]/g,
"");c<a.length;){var d=this._keyStr.indexOf(a.charAt(c++)),g=this._keyStr.indexOf(a.charAt(c++)),e=this._keyStr.indexOf(a.charAt(c++)),k=this._keyStr.indexOf(a.charAt(c++));d=d<<2|g>>4;g=(g&15)<<4|e>>2;var p=(e&3)<<6|k;b+=String.fromCharCode(d);64!=e&&(b+=String.fromCharCode(g));64!=k&&(b+=String.fromCharCode(p))}return phplive_base64._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>
d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(a){var b="",c=0;for(c1=c2=0;c<a.length;){var d=a.charCodeAt(c);128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3)}return b}},chat_http_error,st_http,process_throttle;
function add_text(a,b){""!=b&&"undefined"!=typeof chats[a]&&(b=init_timestamps(b.nl2br()),chats[a].trans+=b,a==ces&&(isop||(b=b.xvis()),$("#chat_body").append(b.emos().extract_youtube()),isop&&mapp&&init_external_url(),b.match(/img src/i)?!b.match(/_blank'><img/i)&&("undefined"!=typeof chats[ces].group_chat&&chats[ces].group_chat||chats[ces].op2op)?setTimeout(function(){init_scrolling()},100):setTimeout(function(){init_scrolling()},600):init_scrolling(),"undefined"!=typeof bid&&$("#chat_body :button").prop("disabled",
!0)))}
function add_text_prepare(a,b){var c=cname,d="undefined"!=typeof b?b:$("textarea#input_text").val();d=d.replace(/\u2592~@\u2592/g,"").replace(/"/g,"&quot;").replace(/'/g,"&#39;");var g="undefined"!=typeof addon_whisper&&addon_whisper?addon_whisper:0,e=g&&($("#select_whisper").length&&parseInt($("#select_whisper").val())||d.match(/^((\/w)|( \/w) )/i))?1:0;e&&(d=d.replace(/^((\/w)|( \/w) )/i,""));if(!("undefined"!=typeof chats[ces]&&1===chats[ces].status&&!chats[ces].disconnected||d.match(/^\//)&&!d.match(/^\/nolink /)&&
shortcut_enabled))return isop||g?"undefined"!=typeof chats[ces]&&!chats[ces].status&&chats[ces].initiated?do_alert(0,"Chat invite connecting..."):do_alert(0,"A chat session must be active."):chats[ces].disconnected&&toggle_input_text(),!1;var k=get_microtime();if("undefined"==typeof process_throttle)process_throttle=k;else{var p=k-process_throttle;process_throttle=k;if(500>=p)return!0}d=isop?d.trimreturn().noreturns().tags().vars(null).vars_global():d.trimreturn().noreturns().tags().vars_global();
if(isop&&shortcut_enabled&&d.match(/^\//)&&!d.match(/^\/nolink /))return process_shortcuts(d),!0;d=autolink_it(d);k=d.replace(/p_br/g,"");k=k.replace(/ /g,"");if(""!=k&&"undefined"!=typeof chats[ces]){k=unixtime();p="";if(isop||g){if("undefined"!=typeof chats[ces].group_chat&&chats[ces].group_chat||chats[ces].op2op)p="<img src='"+profile_pic_url+"' width='25' height='25' style='border-radius: 50%;' alt=''> ";chats[ces].op2op?g=parseInt(chats[ces].op2op)==parseInt(isop)?"co":"cv":g&&e?(g="co cw",p=
"(whisper) "):(g="co",$("#select_whisper").length&&(c="&bull; "+c))}else g="cv",chats[ces].processed<=unixtime()-25&&chatting();d="<div class='"+g+"'><span class='notranslate'>"+p+"<b>"+c+"<timestamp_"+k+"_"+g+">:</b></span>&nbsp;"+d+"</div>";a&&add_text(ces,d);"undefined"!=typeof st_http&&(clearTimeout(st_http),st_http=undeefined);st_http=setTimeout(function(){$("#chat_processing").show()},5E3);http_text(d)}toggle_input_btn_enable(!0);"undefined"==typeof b&&$("textarea#input_text").val("");mapp||
mobile||$("textarea#input_text").focus()}function toggle_input_btn_enable(a){return!0}function parent_send_message(a,b){if("undefined"!=typeof window.addEventListener&&"undefined"!=typeof window.postMessage&&"undefined"!=typeof page_origin&&page_origin&&0==page_origin.indexOf("http")){var c='{ "phplive_message": "'+a+'", "phplive_deptid": '+parseInt(b)+" }";parent.postMessage(c,page_origin)}}var st_http_backlog_responses="",st_http_text;function get_microtime(){return(new Date).getTime()}
function input_text_listen(a){var b=a.keyCode;if(a.shiftKey||13!=b&&10!=b)8==b||46==b?""==$("textarea#input_text").val()&&toggle_input_btn_enable(!0):""==$("textarea#input_text").val()?toggle_input_btn_enable(!0):toggle_input_btn_enable(!1);else{if("undefined"!=typeof a.target&&(b=$("textarea#input_text").val(),a.target.selectionStart!=b.length)){var c=b.length-1;a=b.substr(0,a.target.selectionStart-1)+b.substr(a.target.selectionStart,c);$("textarea#input_text").val(a)}add_text_prepare(1)}}
function input_text_listen_check(a){13==a.keyCode&&$("textarea#input_text").val("")}function input_text_typing(a){input_focus();a=$("textarea#input_text").val().trim();if(isop&&shortcut_enabled){if(a.match(/^\//))return!0}else if("undefined"!=typeof addon_whisper&&addon_whisper&&a.match(/^((\/w)|( \/w) )/i))return!0;$("textarea#input_text").val()&&"undefined"==typeof st_typing&&(send_istyping(),st_typing=setTimeout(function(){clear_istyping()},5E3))}
function init_typing(){si_typing=setInterval(function(){"undefined"!=typeof chats[ces]&&(chats[ces].istyping&&!chats[ces].disconnected?($("#chat_vistyping_wrapper").show(),$("#chat_vistyping").fadeTo("slow",1).fadeTo("slow",.2)):$("#chat_vistyping_wrapper").is(":visible")&&($("#chat_vistyping_wrapper").hide(),$("#chat_vistyping").fadeOut("slow")))},1500)}
function init_clear_istyping_check(){"undefined"==typeof ces||"undefined"==typeof chats[ces]||chats[ces].disconnected?$("#chat_vistyping_wrapper").is(":visible")&&($("#chat_vistyping_wrapper").hide(),$("#chat_vistyping").hide()):$("#chat_vistyping_wrapper").is(":visible")?(chats[ces].istyping_counter+=1,60<chats[ces].istyping_counter&&($("#chat_vistyping_wrapper").hide(),$("#chat_vistyping").hide(),chats[ces].istyping=0,clear_istyping(2))):0<chats[ces].istyping_counter&&(chats[ces].istyping_counter=
0)}function init_scrolling(){"undefined"!=typeof chats&&"undefined"!=typeof chats[ces]&&(chats[ces].disconnected?setTimeout(function(){$("#chat_body").prop("scrollTop",$("#chat_body").prop("scrollHeight"))},500):$("#chat_body").prop("scrollTop",$("#chat_body").prop("scrollHeight")))}function init_textarea(){return!0}
function init_divs(a){phplive_init_orientation_set();1<a&&(mapp=a,a=0);var b=$("#chat_footer").height()?$("#chat_footer").height():0,c=$("#chat_body").css("padding-left"),d="undefined"!=typeof c?20-2*c.replace(/px/,""):0,g=mapp&&mobile&&1!=mapp?mapp:$(window).height();c=mapp&&mobile&&1!=mapp?screen.width:$(window).width();var e=g,k="undefined"!=typeof isop&&parseInt(isop)?c-450:c-42;if(embed){var p=$("#chat_embed_header").height()+7;$("#chat_embed_header").show();e=e-$("#chat_embed_header").height()-
5;$("#info_disconnect").css({top:p})}p=k;if("undefined"!=typeof isop&&parseInt(isop)){var f=g-153;p=mobile?f+55:f+30;var h=k+40,m=f-80,l=g-90;mapp&&(l=g);g=f-($("#chat_info_header").height()+$("#chat_info_menu_list").height())-24-55;h=k+40;var n=h+5,A=p-5,z=h+$("#chat_btn").outerWidth(),B=z-20,y="undefined"!=typeof $("#input_text").css("padding-top")?parseInt($("#input_text").css("padding-top").replace(/px/,"")):0;e=1==mapp?e-b-205:e-b-215;p=k+d;b=k+17;mapp?(e+=45,e=2==mobile?e-25:e-$("#chat_options").outerHeight(),
b=c-$("#chat_btn").width()-50,$("#chat_btn").css({bottom:"85px",right:"5px"})):(b=b-110-(y-5),$("#chat_btn").css({top:A,left:n}));mapp&&5<y?$("#input_text").css({padding:"5px"}):!a&&5<y&&(b-=2*(y-5),c=parseInt($("#input_text").css("height").replace(/px/,"")),c-=2*(y-5),$("#input_text").css({height:c}));$("#chat_input").css({bottom:"auto"});$("#input_text").css({width:b});$("#chat_body").css({height:e,width:p});$("#chat_data").css({top:30,left:h,height:f,width:410});$("#chat_info_body").css({"max-height":g});
$("#chat_info_wrapper_network").css({height:g});$("#chat_panel").css({bottom:55,left:z});mapp?$("#chat_status_offline").css({bottom:200,left:15}):$("#chat_status_offline").css({top:m,left:B});$("#chat_extra_wrapper").css({height:l}).hide();a?(clearTimeout(st_resize),st_resize=setTimeout(function(){close_extra(extra)},800)):close_extra(extra)}else p=k+d,"undefined"!=typeof view?(e-=$("#table_info").height(),e-=100):(e=e-$("#chat_profile_pic").height()-$("#chat_options").outerHeight()-$("#chat_input_wrapper").height()-
64,50>e?(e=e+$("#chat_profile_pic").height()+15,$("#chat_profile_pic").hide()):$("#chat_profile_pic").show()),mobile&&!phplive_orientation_isportrait&&3!=mobile&&2!=mobile&&(e+=35),"undefined"!=typeof view?(e+=6,$("#chat_body").css({height:e,width:p})):(b=$("#input_text").width(),$("#chat_body").css({height:e}))}
function update_ces(a){a.text=text_decode(a.text);var b=a.ces,c=a.text,d=1,g=1;if("undefined"!=typeof chats[b]&&!chats[b].disconnected&&c&&"<>"!=c){chats[b].fmindex=parseInt(a.fmindex);chats[b].fmsize=parseInt(a.fmsize);a=chats[b].fmlid;for(var e=a.split(","),k=0;k<e.length;++k)if(""!=e[k]){var p=e[k];c=c.replace(new RegExp("\x3c!--begin:"+p+"--\x3e(.*?)\x3c!--end:"+p+"--\x3e","g"),"")}10<e.length&&(a=a.replace(/^(.*?),/,""),chats[b].fmlid=a);c=c.replace(/<><>/g,"<>");c=c.replace(/<><>/g,"<>");c=
c.replace(/<><>/g,"<>");if("<>"!=c){c=c.replace(/(?:\r\n|\r|\n)/g,"<br>");a=init_timestamps(c);if(-1!=c.indexOf("<x-voice_chat>"))if(addon_voice_chat)if(isop&&"undefined"!=typeof peer_object)if("undefined"!=typeof peer_object.status&&peer_object.ces!=b)a=a.replace(/<x-voice_chat_button>(.*?)<\/x-voice_chat_button>/g,"<div style='margin-top: 15px;'>You are in an exiting Voice Chat session.  Joining a new Voice Chat is not available.</div>");else{if(!chats[b].op2op_||chats[b].op2op_&&chats[b].op2op==
isop)a=a.replace(/class='btn_op_hide'/g,"style='display: none;'")}else isop&&!peer&&(!chats[b].op2op_||chats[b].op2op_&&chats[b].op2op_==isop)&&(a=a.replace(/class='btn_op_hide'/g,"style='display: none;'"));else a=a.replace(/class='btn_op_hide'/g,"style='display: none;'");chats[b].chatting=1;chats[b].trans+=a;if(-1!=c.indexOf("</top>")&&!parseInt(isop)){e=/<top>(.*?)</;e.test(c)&&(e=e.exec(c),chats[b].oname=e[1],$("#chat_vname").html(e[1]));e=/\x3c!--opid:(.*?)--\x3e/;if(e.test(c)){var f=e.exec(c);
isop_=f[1]}e=/\x3c!--mapp:(.*?)--\x3e/;e.test(c)&&(f=e.exec(c),chats[b].mapp=f[1]);e=/\x3c!--name:(.*?)--\x3e/;e.test(c)&&(f=e.exec(c),$("#chat_profile_name").html(f[1]));e=/\x3c!--department:(.*?)--\x3e/;e.test(c)&&(f=e.exec(c),$("#chat_department_name").html(f[1]));e=/\x3c!--profile_pic:(.*?)--\x3e/;e.test(c)&&(f=e.exec(c),f[1]?$("#td_chat_profile_pic_img").fadeOut("fast").promise().done(function(){$("#chat_profile_pic_img").html("<img src='"+f[1]+"' width='55' height='55' border='0' alt='' class='profile_pic_img' style='border-radius: 50%;'>");
$("#td_chat_profile_pic_img").fadeIn("fast")}):$("#td_chat_profile_pic_img").fadeOut("fast"))}e=/\x3c!--vc_init_op:(.*?)--\x3e/;e.test(c)&&(f=e.exec(c),e=f[1],e.match(/\|/)&&(e=e.split("|"),4==e.length&&(k=unixtime(),parseInt(e[0]),p=parseInt(e[1]),isop&&(!chats[b].op2op_||chats[b].op2op_&&chats[b].op2op==isop)&&p>k-peer_request_expire&&addon_voice_chat&&"function"==typeof vc_init_op&&vc_init_op(e[2],e[3]))));e=/\x3c!--vc_init_vis:(.*?)--\x3e/;e.test(c)&&(f=e.exec(c),e=f[1],e.match(/\|/)&&(e=e.split("|"),
4==e.length&&(k=unixtime(),parseInt(e[0]),p=parseInt(e[1]),(!isop||chats[b].op2op_&&chats[b].op2op!=isop)&&p>k-peer_request_expire&&win_voice_chat&&win_voice_chat.vc_connect(e[2],e[3]))));isop||-1==c.indexOf("<x-nod>")||-1!=c.indexOf("<timestamp_")||(d=0);isop&&-1!=c.indexOf("<x-nod>")&&(g=0);isop||(c=c.xvis());-1==c.indexOf("<disconnected>")||chats[b].disconnected||(chats[b].disconnected=unixtime(),isop?(a+="<c615><div style='margin-top: 10px; margin-bottom: 15px;'><button onClick='pre_disconnect()' style='padding: 10px;' class='input_op_button'>close chat</button></div></c615>",
chats[b].trans+="<c615><div style='margin-top: 10px; margin-bottom: 15px;'><button onClick='pre_disconnect()' style='padding: 10px;' class='input_op_button'>close chat</button></div></c615>"):stopit(0));-1==c.indexOf("<restart_router>")||isop||(-1==c.indexOf("<reset_all>")||isop?chats[b].status=2:(rtype=/\x3c!--rtype:(.*?)--\x3e/.exec(a)[1],e=/\x3c!--deptid:(.*?)--\x3e/.exec(a),chats[b].deptid=e[1],chats[b].status=0,chats[b].processed=unixtime(),deptid=chats[b].deptid,rstring=""),routing(0));if("undefined"!=
typeof bid&&bid){if(phplive_session_support){e=/\x3c!--bsid:(.*?)--\x3e/;if(e.test(c)){e=e.exec(c);bsid="0"!=e[1]?e[1]:bsid;try{localStorage.setItem("bsid",bsid)}catch(h){}}e=/\x3c!--brid:(.*?)--\x3e/;if(e.test(c)){brid=e.exec(c)[1];try{localStorage.setItem("brid",brid)}catch(h){}}}-1!=c.indexOf("\x3c!--start_chat--\x3e")&&setTimeout(function(){bot_start_chat()},1E3)}ces==b&&("undefined"!=typeof bid&&bid&&d?(a=autolink_it(a),$("#chat_body").append(a.emos().extract_youtube().bot_actions()).children(":last").hide().fadeIn(500)):
d&&(a.match(/div_bid_/)?(a=autolink_it(a),$("#chat_body").append(a.emos().extract_youtube()).children(":last").hide().fadeIn(500),setTimeout(function(){$("#chat_body :button").prop("disabled",!0)},100)):$("#chat_body").append(a.emos().extract_youtube()).children(":last").hide().fadeIn(500)),isop&&mapp&&init_external_url(),a.match(/img src/i)?"undefined"!=typeof chats[ces].group_chat&&chats[ces].group_chat||chats[ces].op2op?setTimeout(function(){init_scrolling()},100):setTimeout(function(){init_scrolling()},
600):setTimeout(function(){init_scrolling()},100),init_textarea(),$("#chat_vistyping_wrapper").hide(),$("#chat_vistyping").hide(),chats[b].istyping=0,stopped&&chat_survey(),isop&&"undefined"!=typeof chats[b].auto_canid&&(select_canned_pre(chats[b].auto_canid),chats[b].auto_canid=undeefined,setTimeout(function(){add_text_prepare(1)},1E3)));c=0;isop&&g&&(chats[b].recent_res=unixtime(),ces!=b?menu_blink("green",b):toggle_last_response(1),e=RegExp(chats[b].vname+": ","g"),"undefined"!=typeof dn_enabled_response&&
dn_enabled_response&&chats[b].status&&(a=a.replace(/<span class='notranslate'><b>(.*?):<\/b><\/span>/g," ").replace(/<(.*?)>/g,"").replace(e," ").replace(/\s+/g," ").replace(/&nbsp;/g," ").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\((\d+):(\d+):(\d+)\) :/g,":"),a.match(/Voice Chat ID: /i)||dn_show("new_response",b,"Response: "+chats[b].vname,a,9E5)));if(d&&g){console_blink_r&&(c=1);if(chats[b].status||chats[b].initiated)chat_sound&&play_sound(0,"new_text","new_text_"+sound_new_text),!isop&&
embed&&win_minimized&&(c=1),title_blink_init();c&&flash_console(0)}}}isop&&!mapp&&init_maxc()}
function realtime_update_ces(a){a.text=text_decode(a.text);var b=a.ces,c=a.text.replace(/class='btn_op_hide'/g,"style='display: none;'");if("undefined"!=typeof chats[b]&&c&&"<>"!=c){chats[b].fmindex=parseInt(a.fmindex);chats[b].fmsize=parseInt(a.fmsize);for(var d=chats[b].fmlid,g=d.split(","),e=0;e<g.length;++e)if(""!=g[e]){var k=g[e];c=c.replace(new RegExp("\x3c!--begin:"+k+"--\x3e(.*?)\x3c!--end:"+k+"--\x3e","g"),"")}10<g.length&&(d=d.replace(/^(.*?),/,""),chats[b].fmlid=d);c=c.replace(/<><>/g,
"<>");c=c.replace(/<><>/g,"<>");c=c.replace(/<><>/g,"<>");"<>"!=c&&(chats[b].trans+=c,-1!=a.text.indexOf("<disconnected>")&&(chats[b].disconnected=unixtime(),"undefined"!=typeof realtime&&realtime&&($("#img_spinner_real_time").hide(),$("#req_rating").html("<img src='../themes/"+theme+"/loading_fb.gif' width='16' height='11' border='0' alt=''> closing session..."),setTimeout(function(){$("#req_rating").html('[ <a href="JavaScript:void(0)" onClick="location.reload()">view rating</a> ]')},15E3))),$("#chat_body").append(init_timestamps(c.emos().extract_youtube())).children(":last").hide().fadeIn(500),
setTimeout(function(){init_scrolling()},100),$("#chat_body :button").prop("disabled",!0))}}function text_decode(a){if("undefined"!=typeof a&&a){a=a.split("<>");for(var b="",c=0;c<a.length;++c){var d=phplive_base64.decode(a[c]);b+=d+"<>"}return b}return a}function init_disconnect(){$("#info_disconnect").hover(function(){$(this).removeClass("info_disconnect").addClass("info_disconnect_hover")},function(){$(this).removeClass("info_disconnect_hover").addClass("info_disconnect")})}
var si_timer,timer_previous=0;function init_timer(){"undefined"!=typeof chats[ces]&&(start_timer(chats[ces].timer),"undefined"==typeof si_timer&&(si_timer=setInterval(function(){"undefined"!=typeof chats[ces]&&start_timer(chats[ces].timer)},1E3)))}
function start_timer(a){var b=unixtime();if("undefined"!=typeof chats[ces]){a=chats[ces].disconnected?chats[ces].disconnected-a:b-a;var c=Math.floor(a/3600),d=Math.floor((a-3600*c)/60),g=a-3600*c-60*d;d=pad(d,2)+":"+pad(g,2);c&&(d=pad(c,2)+":"+d);chats[ces].status||chats[ces].initiated?(timer_previous!=a&&$("#chat_vtimer").html(d),timer_previous=a,!(isop||a%10||chats[ces].disconnected)&&chats[ces].processed<=b-25&&(console.log("Chatting process restarted."),chatting())):"00:00"!=$("#chat_vtimer").text()&&
$("#chat_vtimer").html("00:00")}}
function chat_survey(){if(!isop&&!chats[ces].survey&&(chats[ces].survey=1,close_misc("all"),chat_end_message&&(chat_end_message="<div class='ca' id='div_chat_end_message'>"+chat_end_message+"</div>"),add_text(ces,chat_end_message+"<div style='margin-top: 15px; height: 1px;'></div>"),$("#div_chat_end_message a").click(function(b){b.preventDefault();window.open($(this).attr("href"),"_blank")}),chats[ces].rate))if(""==chat_end_message)if($("#chat_body").removeAttr("onclick"),mobile){var a=$("#div_chat_rate_title").html();
$("#div_chat_rate_title").css({"text-align":"center"});add_text(ces,"<div class='ctitle cl' onClick=\"toggle_rating(0);close_misc('attach');close_misc('trans');close_misc('emo');\" style=\"padding: 10px; text-align: center; cursor: pointer;\">"+a+"</div>")}else a="<div id='chat_survey_content' class='info_content'>"+$("#chat_survey_rating").html().replace(/\r?\n|\r/g,"")+"</div>",$("#chat_survey_rating").remove(),$("#chat_body").append(a).children(":last").hide().fadeIn(500),init_scrolling(),chats[ces].trans+=
a;else $("#div_chat_rate_title").css({"text-align":"center"}),$("#chat_survey_wrapper").show();window.onbeforeunload=null;embed&&!win_minimized&&$("#embed_win_close").show();$("#info_disconnect").hide()}
function do_print(a,b,c,d,g){var e="Print_Transcript_"+a;b="undefined"!=typeof chats[a].deptid?parseInt(chats[a].deptid):parseInt(b);"undefined"!=typeof chats[a].opid?parseInt(chats[a].opid):parseInt(c);a=base_url_full+"/ops/op_print.php?ces="+a+"&deptid="+b+"&opid="+c+"&"+unixtime()+"&";wp?"undefined"==typeof view?wp_new_win(a,e,d,g):location.href=a:(newwin_print=window.open(a,e,"scrollbars=yes,menubar=no,resizable=1,location=no,width="+d+",height="+g+",status=0"),setTimeout(function(){newwin_print.focus()},
300))}function init_timestamps(a,b){for(var c=a.split("<>"),d="",g=0;g<c.length;++g){var e=c[g],k=e.match(/timestamp_(\d+)_/);null!=k?(k=extract_time(k[1],b),k=b?timestamp?" <span class='ct'>"+k+"</span> ":"":timestamp?" <span class='ct'>("+k+")</span> ":"",d+=e.replace(/<timestamp_(\d+)_((co)|(cv))>/,k)):d+=e}return d}
function extract_time(a,b){var c=new Date(1E3*parseInt(a)),d=c.getMonth(),g=c.getDate(),e=c.getFullYear(),k=c.getHours(),p=12<=k?" pm":" am";13<=k&&12==time_format&&(k-=12);12!=time_format&&(p="");c=pad(k,2)+":"+pad(c.getMinutes(),2)+":"+pad(c.getSeconds(),2);return b?"<span id='span_timestamp_"+b+"' style='display: none;'>("+c+p+", "+d+"/"+g+"/"+e+")</span>":c}function input_focus(){focused||(focused=1)}var play_sound_success=!1;
function play_sound(a,b,c){unixtime();var d=$("#div_sounds_"+b).html();if(mp3_support){"new_text_default"==c&&(c="new_text_return");"new_text_return"==c&&(c="new_text_return_android");var g=$("#div_sounds_audio_"+b);if("new_request"==b&&!d&&g[0].paused||"new_request"!=b)if($("#div_sounds_"+b).html("on"),$("#div_sounds_audio_"+b).attr("src",base_url+"/media/"+c+".mp3"),a&&(g[0].loop=!0),g[0].volume=sound_volume,a=g[0].play(),void 0!==a)a.then(function(){play_sound_success=!0})["catch"](function(e){})}}
function clear_sound(a){if(mp3_support){var b=$("#div_sounds_audio_"+a);"undefined"!=typeof b[0]&&b[0].pause()}$("#div_sounds_"+a).html()&&$("#div_sounds_"+a).html("")}function vis_check_sound(){var a=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);mp3_support&&!mobile&&a&&!play_sound_success&&play_sound(0,"new_text","new_text_sound_check")}
function title_blink_init(){if(mapp)return!0;"undefined"==typeof title_orig||parseInt(focused)||("undefined"!=typeof si_title&&clearInterval(si_title),"undefined"!=typeof embed&&parseInt(embed)||(si_title=setInterval(function(){title_blink(1,title_orig,"Alert __________________ ")},800)))}
function title_blink(a,b,c){if(mapp)return!0;parseInt(focused)||"reset"==c?"undefined"!=typeof si_title&&(clearInterval(si_title),si_title=undeefined,document.title=b,toggle_favicon(!1)):(si_counter%2&&a?(document.title=c,toggle_favicon(!0)):(document.title=b,toggle_favicon(!1)),++si_counter)}
function toggle_favicon(a){var b=base_url+"/favicon.ico",c=base_url+"/favicon_focus.ico";document.head=document.head||document.getElementsByTagName("head")[0];var d=document.createElement("link");d.rel="shortcut icon";d.href=a?c:b;document.head&&document.head.appendChild(d)}function print_chat_sound_image(a){chat_sound?$("#chat_sound").attr("src",base_url+"/themes/"+a+"/sound_on.png"):$("#chat_sound").attr("src",base_url+"/themes/"+a+"/sound_off.png")}
function flash_console(a){if("undefined"!=typeof mapp&&mapp)return!0;++a;a%2?$("#chat_canvas").addClass("chat_canvas_alert"):$("#chat_canvas").removeClass("chat_canvas_alert");"undefined"!=typeof st_flash_console&&clearTimeout(st_flash_console);st_flash_console=setTimeout(function(){flash_console(a)},1E3)}
function clear_flash_console(){if("undefined"!=typeof mapp&&mapp)return!0;"undefined"!=typeof st_flash_console&&(clearTimeout(st_flash_console),st_flash_console=undeefined,$("#chat_canvas").removeClass("chat_canvas_alert"),"undefined"!=typeof title_orig&&title_blink(0,title_orig,"reset"))}
function close_misc(a){isop&&(clear_flash_console(),toggle_last_response(1));var b=[];"all"==a?(b.push("toggle_emo_box"),b.push("toggle_file_attach"),b.push("toggle_send_trans"),b.push("toggle_rating"),b.push("toggle_screenshot")):"emo"==a?b.push("toggle_emo_box"):"attach"==a?b.push("toggle_file_attach"):"trans"==a?b.push("toggle_send_trans"):"rating"==a?b.push("toggle_rating"):"screenshot"==a&&b.push("toggle_screenshot");for(a=0;a<b.length;++a){var c=b[a];"toggle_emo_box"==c&&"function"==typeof toggle_emo_box?
toggle_emo_box(1):"toggle_file_attach"==c&&"function"==typeof toggle_file_attach?toggle_file_attach(1):"toggle_send_trans"==c&&"function"==typeof toggle_send_trans?toggle_send_trans(1):"toggle_rating"==c&&"function"==typeof toggle_rating?toggle_rating(1):"toggle_screenshot"==c&&"function"==typeof toggle_screenshot&&toggle_screenshot(1)}}function textarea_listen(){return!0}
function start_win_status_listener(){"undefined"!=typeof si_win_status&&clearInterval(si_win_status);si_win_status=setInterval(function(){var a=0;try{a=$("#chat_embed_header").width()}catch(b){}if(a)if(300>a)win_minimized||($("#embed_win_maximize").show(),$("#chat_embed_title").css({opacity:"1"}),$("#embed_win_minimize").hide(),$("#embed_win_popout").hide(),$("#embed_win_close").hide(),$("#info_disconnect").hide(),$("#login_alert_box").hide(),$("#chat_input_wrapper").hide(),"undefined"!=typeof marquee_enabled&&
$(".marquee").hide(),$("#div_policy").length&&toggle_policy(deptid,1),"undefined"==typeof chats?($(window).scrollTop(0),$("#request_body").animate({scrollTop:0},200,function(){$(window).scrollTop(0)})):close_misc("all")),win_minimized=1;else{if(win_minimized||"undefined"==typeof win_minimized)$("#embed_win_maximize").hide(),"undefined"!=typeof preview&&2==parseInt(preview)||$("#chat_embed_title").css({opacity:"0"}),$("#embed_win_minimize").show(),$("#chat_input_wrapper").show(),"undefined"!=typeof marquee_enabled&&
$(".marquee").show(),"undefined"==typeof chats||chats[ces].disconnected||$("#info_disconnect").show(),("undefined"==typeof chats||chats[ces].disconnected)&&$("#embed_win_close").show(),"undefined"==typeof chats&&($(window).scrollTop(0),$("#request_body").animate({scrollTop:0},200,function(){$(window).scrollTop(0)})),clear_flash_console();win_minimized=0}},10)}
function start_new_response_listner(){var a=0;"undefined"!=typeof si_new_response&&clearInterval(si_new_response);si_new_response=setInterval(function(){win_minimized?"undefined"==typeof st_flash_console||a||(a=1,setTimeout(function(){$("#embed_win_maximize_img").attr("src",new_response_image)},200)):(a=0,$("#embed_win_maximize_img").attr("src","./themes/"+theme+"/win_max.png?"+version))},150)}
function phplive_init_orientation_set(){var a=$(window).width(),b=$(window).height();2===phplive_mobile&&(a=screen.width,b=screen.height);phplive_orientation_isportrait=b>a?1:0}var browser_filter=[].filter?1:0,browser_promise="undefined"!=typeof Promise?1:0;function webkit_version(){var a=/AppleWebKit\/([\d.]+)/.exec(navigator.userAgent);return a?parseFloat(a[1]):0}var timestamp_st_requesting=0;
function get_chatting_query(){var a="",b=0,c="",d="",g="",e="",k="",p="",f;for(f in chats)!(1==chats[f].status||!isop&&2==chats[f].status||chats[f].op2op||chats[f].initiated)||chats[f].disconnected||chats[f].tooslow||(c+="qcc[]="+f+"&",d+="qch[]="+chats[f].chatting+"&",g+="qo_[]="+chats[f].op2op+"&",e+="qo__[]="+chats[f].opid+"&",k+="fi[]="+chats[f].fmindex+"&",p+="fs[]="+chats[f].fmsize+"&",b=1);b&&"undefined"!=typeof ces&&"undefined"!=typeof chats[ces]&&(a="rq="+chats[ces].requestid+"&o="+isop+
"&o_="+isop_+"&o__="+isop__+("undefined"!=typeof bid&&bid?"&b="+bid:"")+"&c="+ces+"&ch="+c_chatting+"&"+c+d+g+e+k+p+"&mo="+("undefined"!=typeof mobile?mobile:0)+"&mp="+(isop?mapp:chats[ces].mapp)+"&");return a.replace(/&&/g,"&")}function process_chat_messages(a,b){for(var c="undefined"!=typeof ces?ces:"",d="undefined"!=typeof a?a.length:0,g=0;g<d;++g)update_ces(a[g]);init_chats();"undefined"!=typeof chats[c]&&(chats[c].istyping=b)}function reset_chatting(){reconnect=stopped=0}
var restart_requesting_counter=0,st_restart_requesting;
function restart_requesting(a){++restart_requesting_counter;var b=VARS_JS_REQUESTING+1;"undefined"!=typeof st_network&&(clearTimeout(st_network),st_network=undeefined);"undefined"!=typeof st_requesting&&(clearTimeout(st_requesting),st_requesting=undeefined);"undefined"!=typeof st_restart_requesting&&(clearTimeout(st_restart_requesting),st_restart_requesting=undeefined);st_restart_requesting=setTimeout(function(){"undefined"!=typeof st_network&&(clearTimeout(st_network),st_network=undeefined);"undefined"!=
typeof st_requesting&&(clearTimeout(st_requesting),st_requesting=undeefined);"undefined"!=typeof st_restart_requesting&&(clearTimeout(st_restart_requesting),st_restart_requesting=undeefined);requesting();write_debug("Requesting process restarted. [ COMPLETE ("+a+") "+restart_requesting_counter+"]","")},1E3*b)}function visitor_reconnect(){"undefined"!=typeof st_chatting&&(clearTimeout(st_chatting),st_chatting=undeefined);st_chatting=setTimeout("chatting()",1E3*VARS_JS_REQUESTING)}
function stopit(a){reconnect=a;clear_timeouts();isop||disconnect_complete()}
function clear_timeouts(){"undefined"!=typeof st_routing&&(clearTimeout(st_routing),st_routing=undeefined);"undefined"!=typeof st_chatting&&(clearTimeout(st_chatting),st_chatting=undeefined);"undefined"!=typeof st_requesting&&(clearTimeout(st_requesting),st_requesting=undeefined);"undefined"!=typeof st_queueing&&(clearTimeout(st_queueing),st_queueing=undeefined);"undefined"!=typeof st_network&&(clearTimeout(st_network),st_network=undeefined);"undefined"!=typeof st_reconnect&&(clearTimeout(st_reconnect),
st_reconnect=undeefined);"undefined"!=typeof isop&&isop&&!stopped&&write_debug("All process stopped.","");stopped=1}function set_cookie(a,b,c){unixtime();/MSIE|Trident/.test(window.navigator.userAgent);document.cookie=proto?a+"="+b+"; Secure; SameSite=Strict; path=/;":a+"="+b+"; SameSite=Strict; path=/;"}
String.prototype.extract_youtube=function(){var a=this;if(browser_filter&&(!mobile||!isop))for(var b=a;b.match(/<a href='((http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?)'/i);){unixtime();var c=RegExp.$1,d=$("#chat_body").width(),g=$("#chat_body").height();d=d>g?g:d;d=300>d?300:d-25;c=createVideo(c,"100%",d);"boolean"!=typeof c&&(a=b=b.replace(/<a href='(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?' target='_blank' rel='noopener noreferrer'>(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?<\/a>/i,
c.get(0).outerHTML))}return a};function select_days_options(a,b,c){a=parseInt(a);c=parseInt(c);$("#day_day").empty().hide();if(a&&c){c=(new Date(c,a,0)).getDate();a="<option value=0></option>";for(var d=1;d<=c;d++)a+="<option value='"+d+"' "+(b==d?"selected":"")+">"+d+"</option>";$("#day_day").append(a).show()}}var win_voice_chat;
function vc_join(a,b,c,d){var g=b+d+c+unixtime();win_voice_chat=window.open(base_url_full+"/addons/voice_chat/voice_chat.php?rid="+a+"&opid="+c+"&ces="+b+"&theme="+theme+"&token="+d,g)};