function init_lang_texts(a){var b="undefined"!=typeof depts_lang[a]?depts_lang[a]:"english",c;if("undefined"!=typeof LANG_TEXTS[b]){b=jQuery.extend(!0,{},LANG_TEXTS[b]);for(c in b)"undefined"!=typeof LANG_DBS[a]&&"undefined"!=typeof LANG_DBS[a][c]&&(b[c]=decodeURIComponent(LANG_DBS[a][c]));LANG_MERGED=jQuery.extend(!0,{},b);LANG_MERGED.TXT_LIVECHAT=LANG_MERGED.TXT_LIVECHAT.substring(0,20);$("*","body").find("span").each(function(){var d=this.id;0==d.indexOf("LANG_")&&$(this).html(LANG_MERGED[d.slice(5)])});
$("#vdeptid option").each(function(){var d=$(this).attr("class");if(d){var f=$(this).val(),e=-1!=d.indexOf("online")?LANG_MERGED.TXT_ONLINE:LANG_MERGED.TXT_OFFLINE;-1!=d.indexOf("botonline")&&dept_settings[f][4]&&(e="Bot "+e);$(this).text($(this).text().replace(/ \((.*?)$/," ("+e+")"))}});$("#vdeptid option").eq(0).text(LANG_MERGED.CHAT_SELECT_DEPT)}else do_alert(0,"Language file not found ["+b+"].")}
function init_divs_pre(){var a=$("#request_body").css("padding-left");a="undefined"!=typeof a?parseInt(a.replace(/px/,"")):0;var b=$("#vdeptid").length?$("#vdeptid").css("padding-top").replace(/px/,""):8;b-=5;var c=$("body").height()-(mobile?140:150);c=embed?c-$("#chat_embed_header").height():c+7;c-=Math.floor(a/2)+10;c+="px";var d="15px";var f=$("body").width()-2*a+"px";a+="px";var e=$("#request_body").width(),g=e-18;b=Math.floor(e/2)-25-b;$("#request_body").css({height:c});$("#table_pre_chat_form_table").css({width:f});
$("#chat_text_powered").css({"margin-right":a,"font-size":"10px"});$("#chat_submit_btn").css({"margin-left":a,"margin-top":d});$("#vdeptid").css({width:e});$("#vname").css({width:b});mobile||!$("#vname").length||browser_filter||$("#vname").focus();$("#vemail").css({width:b});$("#vsubject").css({width:b});$("#vquestion").css({width:g});$("#custom_field_input_0").css({width:"100%"});$("#custom_field_input_1").css({width:b});$("#custom_field_input_2").css({width:b});$("#custom_field_input_3").css({width:b});
$("#custom_field_input_4").css({width:b});$("#div_online_pics").css({width:g});mobile&&($("#vquestion").css({height:"45px"}),VARS_MISC_MOBILE_MAX_QUIRK&&$("body :input").each(function(){$(this).css({"font-size":"16px"})}))}var show_divs;
function select_dept(a){a=parseInt(a);if(!preview&&!redirected&&a&&1E8>a&&"undefined"!=typeof dept_settings[a][7]&&dept_settings[a][7]&&(dept_settings[a][4]||"offline"!=$("#vdeptid option:selected").attr("class"))){var b=location.href;b=b.match(/d=(\d+)&/)?b.replace(/d=(\d+)&/,"d="+a+"&"):b.match(/&d=(\d+)/)?b.replace(/&d=(\d+)/,"&d="+a):b+"&d="+a;if("undefined"==typeof bot_form[a])return location.href=b,!0}a||$("#tr_files").hide();init_lang_texts(a);$("#deptid").val(a);$("#custom_field_input_1").val("");
$("#custom_field_input_2").val("");$("#custom_field_input_3").val("");$("#custom_field_input_4").val("");$("#div_offline_url").hide();show_divs={vname:{}};"undefined"!=typeof dept_settings[a]&&dept_settings[a][3]||!a?($("#optional_name").html(""),show_divs.vname.required=1,show_divs.vname.optional=""):($("#optional_name").html(" ("+LANG_MERGED.TXT_OPTIONAL+")"),show_divs.vname.required=0,show_divs.vname.optional=" ("+LANG_MERGED.TXT_OPTIONAL+")");show_divs.vemail={};"undefined"!=typeof dept_settings[a]&&
dept_settings[a][0]||!a?($("#optional_email").html(""),show_divs.vemail.required=1,show_divs.vemail.optional=""):($("#optional_email").html(" ("+LANG_MERGED.TXT_OPTIONAL+")"),show_divs.vemail.required=0,show_divs.vemail.optional=" ("+LANG_MERGED.TXT_OPTIONAL+")");custom_required4=custom_required3=custom_required2=custom_required=0;$("#div_customs").hide();$("#div_customs2").hide();$("#div_customs3").hide();a&&"undefined"!=typeof dept_customs[a]&&(custom_required=dept_customs[a][1],show_divs.custom_field_input_1=
{},dept_customs[a][0]?show_divs.custom_field_input_1.required=custom_required:custom_required=0,show_divs.custom_field_input_1.optional=custom_required?"":" ("+LANG_MERGED.TXT_OPTIONAL+")",show_divs.custom_field_input_1.title=dept_customs[a][0],show_divs.custom_field_input_1.value="undefined"!=typeof custom_hash[dept_customs[a][0]]?custom_hash[dept_customs[a][0]]:"",custom_required2=dept_customs[a][3],show_divs.custom_field_input_2={},dept_customs[a][2]?show_divs.custom_field_input_2.required=custom_required2:
custom_required2=0,show_divs.custom_field_input_2.optional=custom_required2?"":" ("+LANG_MERGED.TXT_OPTIONAL+")",show_divs.custom_field_input_2.title=dept_customs[a][2],show_divs.custom_field_input_2.value="undefined"!=typeof custom_hash[dept_customs[a][2]]?custom_hash[dept_customs[a][2]]:"",custom_required3=dept_customs[a][5],show_divs.custom_field_input_3={},dept_customs[a][4]?show_divs.custom_field_input_3.required=custom_required3:custom_required3=0,show_divs.custom_field_input_3.optional=custom_required3?
"":" ("+LANG_MERGED.TXT_OPTIONAL+")",show_divs.custom_field_input_3.title=dept_customs[a][4],show_divs.custom_field_input_3.value="undefined"!=typeof custom_hash[dept_customs[a][4]]?custom_hash[dept_customs[a][4]]:"",custom_required4=dept_customs[a][7],show_divs.custom_field_input_4={},dept_customs[a][6]?show_divs.custom_field_input_4.required=custom_required3:custom_required4=0,show_divs.custom_field_input_4.optional=custom_required4?"":" ("+LANG_MERGED.TXT_OPTIONAL+")",show_divs.custom_field_input_4.title=
dept_customs[a][6],show_divs.custom_field_input_4.value="undefined"!=typeof custom_hash[dept_customs[a][6]]?custom_hash[dept_customs[a][6]]:"");$("#chat_text_header").show();if("offline"==$("#vdeptid option:selected").attr("class")){onoff=0;$("#chat_text_header").html(LANG_MERGED.MSG_LEAVE_MESSAGE);$("#chat_text_header_sub").html(autolink_it(dept_offline[a]));parseInt(js_email)&&(show_divs.vemail.disabled=1);show_divs.vsubject={};show_divs.vsubject.required=1;show_divs.vquestion={};show_divs.vquestion.required=
1;show_divs.vquestion.optional="";show_divs.vemail.required=1;$("#chat_button_start").html(LANG_MERGED.CHAT_BTN_EMAIL).off("click").on("click",function(){send_email()});if("undefined"!=typeof dept_offline_urls[0]||"undefined"!=typeof dept_offline_urls[a])dept_offline_form[a]=0;if("undefined"!=typeof dept_offline_form[a])if(parseInt(dept_offline_form[a]))$("#table_pre_chat_form").show(),$("#chat_submit_btn").css("opacity","1");else{if($("#table_pre_chat_form").hide(),$("#chat_submit_btn").css("opacity",
"0.0"),$("#chat_button_start").prop("onclick",null).off("click"),"undefined"!=typeof dept_offline_urls[0]||"undefined"!=typeof dept_offline_urls[a])b="undefined"!=typeof dept_offline_urls[a]?dept_offline_urls[a]:dept_offline_urls[0],$("#chat_button_start").off("click"),$("#div_offline_url").html('<big><a href="'+b+'" target="_top">'+b+"</a></big>").show()}else $("#table_pre_chat_form").show(),$("#chat_submit_btn").css("opacity","1");"undefined"!=typeof dept_settings[a]&&dept_settings[a][5]?(b=dept_settings[a][5],
1==b?b="GIF,PNG,JPG,JPEG,PDF,ZIP,TAR,TXT,TEXT,CONF":b&&(b.match(/jpg/i)&&!b.match(/jpeg/i)&&(b+=",JPEG"),b.match(/txt/i)&&!b.match(/text/i)&&(b+=",TEXT")),$("#attach_uf").val(phplive_base64.encode(b)),$("#tr_files").show()):($("#attach_uf").val(""),$("#tr_files").hide(),"undefined"!=typeof vis_attach_reset&&vis_attach_reset(),"undefined"!=typeof screenshot_delete&&screenshot_delete());embed&&!phplive_mobile&&browser_promise&&"undefined"!=typeof dept_settings[a]&&dept_settings[a][6]?$("#tr_screenshot").show():
$("#tr_screenshot").hide()}else{onoff=1;$("#chat_text_header").html(LANG_MERGED.CHAT_WELCOME);$("#chat_text_header_sub").html(autolink_it(LANG_MERGED.CHAT_WELCOME_SUBTEXT));a&&"undefined"!=typeof dept_settings[a]&&(dept_settings[a][0]&&parseInt(js_email)&&(show_divs.vemail.disabled=1),show_divs.vquestion={},dept_settings[a][2]?(show_divs.vquestion.required=1,show_divs.vquestion.optional=""):(show_divs.vquestion.required=0,show_divs.vquestion.optional=" ("+LANG_MERGED.TXT_OPTIONAL+")"));if(a&&1E8>=
a)$("#chat_button_start").html(LANG_MERGED.CHAT_BTN_START_CHAT).off("click").on("click",function(){start_chat()});else $("#chat_button_start").html(LANG_MERGED.TXT_SUBMIT).attr("disabled",!1).off("click").on("click",function(){start_chat()});dept_offline_hasform&&($("#table_pre_chat_form").show(),$("#chat_submit_btn").css("opacity","1"));$("#attach_uf").val("");$("#tr_files").hide();"undefined"!=typeof vis_attach_reset&&vis_attach_reset();"undefined"!=typeof screenshot_delete&&screenshot_delete()}"undefined"!=
typeof dept_haspolicy[a]?onoff||!onoff&&dept_offline_form[a]?($("#div_checkbox_data_policy_wrapper").show(),$("#div_notice_text_checkbox").html(decodeURIComponent(dept_haspolicy[a])+' <span id="span_policy_loading" style="display: none;"><img src="./themes/'+theme+'/loading_chat.gif" width="12" height="12" border="0" alt="loading..." title="loading..." class="round"></span>')):$("#div_checkbox_data_policy_wrapper").hide():$("#div_checkbox_data_policy_wrapper").hide();$("#checkbox_data_policy").prop("checked",
!1);(show_divs.vemail.required&&"undefined"!=typeof dept_prechat_form[a]&&parseInt(dept_prechat_form[a])||!onoff)&&"undefined"!=typeof dept_addon_emarketings[a]&&emarketid?onoff||!onoff&&dept_offline_form[a]?$("#div_checkbox_emarketing_wrapper").show():$("#div_checkbox_emarketing_wrapper").hide():$("#div_checkbox_emarketing_wrapper").hide();display_window();init_divs_input(a,onoff);!a||a&&onoff?fetch_online_pics(a):close_online_pics()}
function check_form(a){var b=parseInt($("#deptid").val());if(!a&&"undefined"!=typeof dept_prechat_form[b]&&!parseInt(dept_prechat_form[b])){if("undefined"==typeof dept_haspolicy[b]||$("#checkbox_data_policy").is(":checked"))return $("#skp").val(1),!0;$("#checkbox_data_policy_arrow").show();$("#div_notice_data_policy").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast");return!1}if(!b||1E8<=b)return $("#vdeptid").fadeOut("fast",
function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),do_alert(0,LANG_MERGED.CHAT_JS_CUSTOM_BLANK),!1;var c=1;""==$("#vname").val().replace(/ +/,"")&&$("#vname").val("");!$("#vname").val()&&dept_settings[b][3]&&($("#vname").fadeOut("fast",function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),c=0);$("#vemail").val()||!dept_settings[b][0]&&!a||($("#vemail").fadeOut("fast",function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),
c=0);!$("#vsubject").val()&&a&&($("#vsubject").fadeOut("fast",function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),c&&($("#div_field_3").is(":visible")||$("#div_field_5").is(":visible"))&&$("#request_body").animate({scrollTop:$(document).height()},"slow"),c=0);custom_required&&!$("#custom_field_input_1").val()&&($("#custom_field_input_1").fadeOut("fast",function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),c&&($("#div_field_3").is(":visible")||
$("#div_field_5").is(":visible"))&&$("#request_body").animate({scrollTop:$(document).height()},"slow"),c=0);custom_required2&&!$("#custom_field_input_2").val()&&($("#custom_field_input_2").fadeOut("fast",function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),c&&($("#div_field_3").is(":visible")||$("#div_field_5").is(":visible"))&&$("#request_body").animate({scrollTop:$(document).height()},"slow"),c=0);custom_required3&&!$("#custom_field_input_3").val()&&($("#custom_field_input_3").fadeOut("fast",
function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),c&&($("#div_field_3").is(":visible")||$("#div_field_5").is(":visible"))&&$("#request_body").animate({scrollTop:$(document).height()},"slow"),c=0);custom_required4&&!$("#custom_field_input_0").val()&&($("#custom_field_input_0").fadeOut("fast",function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),c=0);""==($("#vquestion").val()?$("#vquestion").val().replace(/ +/,""):"")&&$("#vquestion").val("");
$("#vquestion").val()||!dept_settings[b][2]&&!a||($("#vquestion").fadeOut("fast",function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),c&&$("#div_field_9").is(":visible")&&$("#request_body").animate({scrollTop:$(document).height()},"slow"),c=0);if(!c)return do_alert(0,LANG_MERGED.CHAT_JS_CUSTOM_BLANK),!1;if(!check_email($("#vemail").val())&&(dept_settings[b][0]||a))return $("#vemail").fadeOut("fast",function(){$(this).fadeIn("fast",function(){$(this).addClass("input_focus")})}),
do_alert(0,LANG_MERGED.CHAT_JS_INVALID_EMAIL),!1;if("undefined"!=typeof dept_addon_emarketings[b]){a=$("#emarket_val_1").is(":checked")?1:0;c=$("#emarket_val_0").is(":checked")?1:0;if(emarketid&&!a&&!c&&emarket_isreq&&show_divs.vemail.required)return $("#request_body").animate({scrollTop:$(document).height()},"slow"),$("#emarketid").val(0),$("#div_checkbox_emarketing_wrapper").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast"),
!1;$("#emarketid").val(emarketid)}else $("#emarketid").val(0);return"undefined"==typeof dept_haspolicy[b]||$("#checkbox_data_policy").is(":checked")?!0:($("#request_body").animate({scrollTop:$(document).height()},"slow"),$("#checkbox_data_policy_arrow").show(),$("#div_notice_data_policy").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast").fadeOut("fast").fadeIn("fast"),!1)}
function send_email(){if(preview)return do_alert(0,"Chat is not available for interface preview."),!1;check_form(1)&&send_email_doit("")}function preview_text(a){"undefined"!=typeof a.TXT_LIVECHAT&&$("#LANG_TXT_LIVECHAT").html(a.TXT_LIVECHAT.substring(0,20));$("#chat_text_header").html(a.CHAT_WELCOME);$("#chat_text_header_sub").html(autolink_it(a.CHAT_WELCOME_SUBTEXT));$("#chat_text_department").html(a.TXT_DEPARTMENT);$("#vdeptid option:eq(0)").text(a.CHAT_SELECT_DEPT)}
function preview_custom(a){dept_settings[deptid]=[a.remail,a.remail,a.rquestion,a.rname,dept_settings[deptid][4]];dept_customs[deptid]=[a.custom1,parseInt(a.custom1_req),a.custom2,parseInt(a.custom2_req),a.custom3,parseInt(a.custom3_req),a.custom4,parseInt(a.custom4_req)];dept_prechat_form[deptid]=parseInt(a.prechat);select_dept(deptid)}function preview_marquee(a){$(".marquee").empty().marquee("destroy");a?$(".marquee").html(decodeURIComponent(a)).show().marquee():$(".marquee").hide()}
function check_mobile_view(a,b){$("#"+a).hasClass("input_focus")&&$("#"+a).removeClass("input_focus")}var st_policy_load;
function toggle_policy(a,b){if($("#div_policy_wrapper").is(":visible")||b)clearTimeout(st_policy_load),$("#span_policy_loading").hide(),$("#div_policy_wrapper").hide(),$("#request_body_wrapper").show(),$("#div_marquee").css({"z-Index":140}),init_divs_pre();else{var c=$("#request_body_wrapper").height()-95,d=c+95;$("#div_policy").css({height:0});st_policy_load=setTimeout(function(){$("#span_policy_loading").fadeIn("fast")},800);$("#div_policy").load("./ajax/actions.php?action=fetch_policy&deptid="+
a,function(){clearTimeout(st_policy_load);$("#div_policy a").click(function(f){f.preventDefault();window.open($(this).attr("href"),"_blank")});$("#request_body_wrapper").hide();$("#div_marquee").css({"z-Index":-1});$("#div_policy_wrapper").css({height:d}).show();$("#div_policy").css({height:c}).scrollTop(0)})}};